# Generated by Django 4.2.8 on 2025-12-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="对象ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "垃圾信息"),
                            ("inappropriate", "不当内容"),
                            ("false_info", "虚假信息"),
                            ("offensive", "攻击性言论"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="举报说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已处理"),
                            ("dismissed", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("handler_note", models.TextField(blank=True, verbose_name="处理备注")),
                ("handled_at", models.DateTimeField(blank=True, null=True, verbose_name="处理时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="举报时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="举报内容类型",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="对象ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "通过"), ("reject", "拒绝"), ("pending", "待审核")],
                        max_length=20,
                        verbose_name="审核动作",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="审核原因/备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="审核时间")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核员",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核日志",
                "verbose_name_plural": "审核日志",
                "db_table": "moderation_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
