# Generated by Django 4.2.8 on 2025-12-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="行业名称")),
                ("description", models.TextField(blank=True, verbose_name="行业描述")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "行业",
                "verbose_name_plural": "行业",
                "db_table": "industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, unique=True, verbose_name="公司名称"
                    ),
                ),
                ("name_en", models.CharField(blank=True, max_length=200, verbose_name="英文名称")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/", verbose_name="公司Logo"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-50", "1-50人"),
                            ("51-200", "51-200人"),
                            ("201-500", "201-500人"),
                            ("501-1000", "501-1000人"),
                            ("1001-5000", "1001-5000人"),
                            ("5001+", "5000人以上"),
                        ],
                        max_length=20,
                        verbose_name="公司规模",
                    ),
                ),
                ("founded_year", models.IntegerField(blank=True, null=True, verbose_name="成立年份")),
                ("website", models.URLField(blank=True, verbose_name="官方网站")),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="总部地址")),
                ("description", models.TextField(blank=True, verbose_name="公司简介")),
                ("review_count", models.IntegerField(default=0, verbose_name="评价数")),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="平均评分"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="已认证")),
                ("is_active", models.BooleanField(default=True, verbose_name="激活状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.industry",
                        verbose_name="所属行业",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司",
                "db_table": "companies",
                "ordering": ["-review_count", "name"],
            },
        ),
    ]
