# Generated by Django 4.2.8 on 2025-12-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("helpful_count", models.IntegerField(default=0, verbose_name="有用数")),
                ("is_anonymous", models.BooleanField(default=True, verbose_name="匿名评论")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reviews.comment",
                        verbose_name="父评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="评价内容（富文本）")),
                ("overall_rating", models.IntegerField(default=5, verbose_name="综合评分")),
                ("welfare_rating", models.IntegerField(default=5, verbose_name="福利待遇")),
                ("environment_rating", models.IntegerField(default=5, verbose_name="工作环境")),
                ("development_rating", models.IntegerField(default=5, verbose_name="发展机会")),
                ("management_rating", models.IntegerField(default=5, verbose_name="管理水平")),
                ("job_title", models.CharField(blank=True, max_length=100, verbose_name="职位")),
                (
                    "employment_status",
                    models.CharField(
                        choices=[("current", "在职"), ("former", "离职")],
                        default="current",
                        max_length=20,
                        verbose_name="就职状态",
                    ),
                ),
                ("work_years", models.IntegerField(blank=True, null=True, verbose_name="工作年限")),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("helpful_count", models.IntegerField(default=0, verbose_name="有用数")),
                ("comment_count", models.IntegerField(default=0, verbose_name="评论数")),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览数")),
                ("is_anonymous", models.BooleanField(default=True, verbose_name="匿名发布")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="companies.company",
                        verbose_name="公司",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评价用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="review_images/", verbose_name="图片")),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="图片说明")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reviews.review",
                        verbose_name="所属评价",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价图片",
                "verbose_name_plural": "评价图片",
                "db_table": "review_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="comment_images/", verbose_name="图片")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reviews.comment",
                        verbose_name="所属评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论图片",
                "verbose_name_plural": "评论图片",
                "db_table": "comment_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.review",
                verbose_name="所属评价",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论用户",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["company", "moderation_status"], name="reviews_company_8cae16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["-created_at"], name="reviews_created_6c5dce_idx"),
        ),
    ]
